apiVersion: v1
kind: Service
metadata:
  name: landingpage
  namespace: landingpage
spec:
  selector:
    app: landingpage
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: NodePort
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80 